"""transactions decimal and created_at

Revision ID: ebbbef38eb55
Revises:
Create Date: 2026-04-14 14:02:14.757067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebbbef38eb55"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=120), nullable=False),
        sa.Column("email", sa.VARCHAR(length=120), nullable=False),
        sa.Column("password", sa.VARCHAR(), nullable=False),
        sa.Column(
            "amount",
            sa.NUMERIC(precision=12, scale=2),
            server_default=sa.text("'0'"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("check_users_amount_non_negative")),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("value", sa.NUMERIC(precision=12, scale=2), nullable=False),
        sa.Column(
            "description",
            sa.VARCHAR(length=255),
            server_default=sa.text("('')"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
